databases:
  - name: prophecy
    databaseName: prophecy
    user: prophecy
    plan: free

services:
  - type: web
    name: prophecy
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prophecy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

  - type: worker
    name: prophecy_worker
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec good_job start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prophecy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false